/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
Traceback (most recent call last):
  File "/home/modelrep/sadiya/tobias_ettling/ML_Models_BrainAge/KernelRidge/training.py", line 61, in <module>
    results.to_csv(BASE_PATH + f'KernalRige/{f_name}results.csv')
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/modelrep/sadiya/tobias_ettling/ML_Models_BrainAge/KernalRige'
