Traceback (most recent call last):
  File "/home/modelrep/sadiya/tobias_ettling/ML_Models_BrainAge/SVRegression/shapValues.py", line 78, in <module>
    explainer = shap.KernelExplainer(best_model.predict, shap.sample(x_train_df, 10), num_jobs=-2)
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/shap/explainers/_kernel.py", line 96, in __init__
    model_null = match_model_to_data(self.model, self.data)
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/shap/utils/_legacy.py", line 123, in match_model_to_data
    out_val = model.f(data.data)
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/sklearn/svm/_base.py", line 431, in predict
    X = self._validate_for_predict(X)
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/sklearn/svm/_base.py", line 608, in _validate_for_predict
    check_is_fitted(self)
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1462, in check_is_fitted
    raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This SVR instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
