Traceback (most recent call last):
  File "/home/modelrep/sadiya/tobias_ettling/ML_Models_BrainAge/RandomForrest/shapValues.py", line 81, in <module>
    explainer = shap.TreeExplainer(best_model, num_jobs=-2)
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/shap/explainers/_tree.py", line 166, in __init__
    self.model = TreeEnsemble(model, self.data, self.data_missing, model_output)
  File "/home/modelrep/sadiya/miniconda/envs/pytorch/lib/python3.9/site-packages/shap/explainers/_tree.py", line 670, in __init__
    assert hasattr(model, "estimators_"), "Model has no `estimators_`! Have you called `model.fit`?"
AssertionError: Model has no `estimators_`! Have you called `model.fit`?
